providers = ["node"]

[variables]
# 基础环境配置
NODE_ENV = "production"
PORT = "3001"

# 前端构建环境变量
VITE_API_URL = "/api"
VITE_APP_TITLE = "占卜应用管理后台"

# 后端配置
JWT_EXPIRES_IN = "7d"
LOG_LEVEL = "info"
CORS_ORIGIN = "https://zwam.vryo.de"

# 注意：敏感信息如 JWT_SECRET, DATABASE_URL 需要在 Coolify 界面中设置

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci || npm install",
  "cd backend && npm ci --only=production",
  "if [ -f zhanwen-admin-vue/package.json ]; then npm install --prefix zhanwen-admin-vue --include=dev; else echo \"[nixpacks] zhanwen-admin-vue not found, skip frontend install\"; fi"
]

[phases.build]
cmds = [
  "if [ -f zhanwen-admin-vue/package.json ]; then npm run build --prefix zhanwen-admin-vue; else echo \"[nixpacks] zhanwen-admin-vue not found, skip frontend build\"; fi",
  "cd backend && npm run build"
]

[start]
cmd = "node backend/dist/index.js"
