-- Add missing is_active column for public_prompts
-- Generated by Cascade on 2025-09-05 15:22:37+08:00

BEGIN;

ALTER TABLE "public_prompts"
  ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT TRUE;

-- Optional but recommended: index for faster filtering
CREATE INDEX IF NOT EXISTS "public_prompts_is_active_idx" ON "public_prompts" ("is_active");

COMMIT;
