-- Drop platform/scene/language from prompt_texts and update unique/indexes
-- Generated by Cascade on 2025-09-08 18:30:10+08:00

BEGIN;

-- Safely drop old unique index if exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname = ANY (current_schemas(false)) AND indexname = 'prompt_texts_unique_name_platform_scene_language_version'
  ) THEN
    EXECUTE 'DROP INDEX IF EXISTS prompt_texts_unique_name_platform_scene_language_version';
  END IF;
END $$;

-- Safely drop old composite index if exists
DROP INDEX IF EXISTS prompt_texts_platform_scene_language_idx;

-- Drop columns if they exist
ALTER TABLE "prompt_texts"
  DROP COLUMN IF EXISTS "platform",
  DROP COLUMN IF EXISTS "scene",
  DROP COLUMN IF EXISTS "language";

-- Create new unique index on (name, version)
CREATE UNIQUE INDEX IF NOT EXISTS prompt_texts_unique_name_version ON "prompt_texts" ("name", "version");

COMMIT;
