-- Create prompt_texts table for three-section prompt texts
-- Generated by Cascade on 2025-09-08 16:57:51+08:00

BEGIN;

CREATE TABLE IF NOT EXISTS "prompt_texts" (
  "id"          SERIAL PRIMARY KEY,
  "name"        VARCHAR(100) NOT NULL,
  "version"     VARCHAR(50)  NOT NULL DEFAULT '1',
  "platform"    VARCHAR(20)  NOT NULL,
  "scene"       VARCHAR(50)  NOT NULL,
  "language"    VARCHAR(10)  NOT NULL,
  "is_active"   BOOLEAN      NOT NULL DEFAULT TRUE,
  "texts"       JSONB        NOT NULL,
  "metadata"    JSONB        NOT NULL DEFAULT '{}',
  "created_at"  TIMESTAMP    NOT NULL DEFAULT NOW(),
  "updated_at"  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Unique constraint for versioned config
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname = ANY (current_schemas(false)) AND indexname = 'prompt_texts_unique_name_platform_scene_language_version'
  ) THEN
    EXECUTE 'CREATE UNIQUE INDEX prompt_texts_unique_name_platform_scene_language_version ON "prompt_texts" ("name", "platform", "scene", "language", "version")';
  END IF;
END $$;

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS "prompt_texts_platform_scene_language_idx" ON "prompt_texts" ("platform", "scene", "language");
CREATE INDEX IF NOT EXISTS "prompt_texts_is_active_idx" ON "prompt_texts" ("is_active");

-- Seed a default active record for quick start (id auto)
INSERT INTO "prompt_texts" (
  "name", "version", "platform", "scene", "language", "is_active", "texts", "metadata"
) VALUES (
  'divination_texts_default',
  '2025-09-01T00:00:00Z',
  'web',
  'divination',
  'zh-CN',
  TRUE,
  $$
  {
    "system_prompt": "你是一名经验丰富的易学专家，精通小六壬占卜的解读和应用。你有多年研究传统中国预测学的经验，能够从卦象中解读出深刻的含义并给予有益的指导。",
    "user_intro": "我需要你根据以下小六壬卦象信息，提供一个详细的解读。",
    "user_guidelines": "请给出详细的解读，包括以下内容：\n1. 卦象综合解析（包括三宫关系和互动的深层含义）\n2. 对用户问题的针对性回答（如果有问题）\n3. 宜忌建议\n4. 未来发展趋势\n5. 化解方法或行动建议\n如果是标题，请用中文数字+顿号开头，如‘一、’；副标题，请用中文数字+.开头，如‘1.’；内容，如果有顺序请用如‘①②③④⑤⑥⑦⑧⑨⑩’ 无顺序用‘-’"
  }
  $$::jsonb,
  '{}'
)
ON CONFLICT ("name", "platform", "scene", "language", "version") DO NOTHING;

COMMIT;
